language: ruby
rvm:
  - 2.4.1
sudo: false
cache: bundler
dist: trusty
install: bundle install --jobs=8 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script:
  - bundle exec middleman build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      git config --global user.name "${GIT_NAME}";
      git config --global user.email "${GIT_EMAIL}";
      git remote set-url origin "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git";
      bundle exec middleman deploy;
    fi
notifications:
  email: false
